### ISSUE TITLE
name for template?

### ISSUE THREAD

**Issue by evanwill** [learn-static/lesson-template#7]
@owikle What do we want to title this template?

- current = "Lesson Template"
- repository = "sidebar-template"

**Comment by owikle** [comment]
Title could be "Learn-Static Lesson Template," and repo name "lesson-template"?

**Comment by dcnb** [comment]
Are you sure? Sounds like your wavering there … 🤷‍♂️

**Comment by evanwill** [comment]
repo renamed `lesson-template`, update your local copy accordingly!
